-- .harness lineage index — schema v5 migration (v0.3.1 drop tag kind).
--
-- Apply AFTER 004_v0_3_notes.sql. The runner skips this file when
-- `_schema.version >= 5`.
--
-- Spec references:
--   - format.md §2.2  — kind enum (init|auto only; no tag)
--   - format.md §4.2  — tags are lightweight refs (normative, not v0.3 limitation)
--   - format.md §9.1  — patch bump from v0.3.0 to v0.3.1
--   - format.md §9.7  — full v0.3.0 → v0.3.1 transition narrative
--
-- Structural changes from schema v4:
--   * REMOVED: `snapshots.version` column. Its only purpose was
--     annotating tag-kind snapshots; with tag-kind gone, the field
--     has no purpose. Any data in this column is dropped by the
--     migration (no real CLI usage ever populated it because
--     `harness tag` writes lightweight refs, not snapshots).
--   * CHANGED: `snapshots.kind` CHECK constraint — `init|auto` (was
--     `init|auto|tag`). Existing `tag`-kind rows are dropped during
--     the rebuild — see the WHERE clause in the INSERT below.
--
-- The migration drops `tag`-kind snapshot rows from the index. Their
-- on-disk JSON blobs (under `.harness/snapshots/`) are NOT rewritten
-- by this SQL file — they become orphans (not loaded by reindex,
-- safe to delete manually). For real CLI users this is a no-op
-- because `harness tag` in v0.3.0 already wrote lightweight refs
-- only; only the example-fixture generator ever produced tag-kind
-- snapshots, and those fixtures are regenerated by the v0.3.1
-- `build_examples.py`.

PRAGMA foreign_keys = OFF;

BEGIN;

-- ─────────────────────────────────────────────────────────────────────
-- Rebuild `snapshots` to drop the `version` column and update the
-- kind CHECK. Tag-kind rows are filtered out by the INSERT's WHERE
-- clause (the new CHECK would reject them anyway).
-- ─────────────────────────────────────────────────────────────────────

CREATE TABLE snapshots_new (
  id              TEXT PRIMARY KEY,
  branch          TEXT NOT NULL,
  kind            TEXT NOT NULL CHECK (kind IN ('init','auto')),
  code_pin        TEXT,
  apm_lock_hash   TEXT,
  author          TEXT,
  created_at      TEXT NOT NULL,
  format_version  TEXT NOT NULL DEFAULT '0.3',
  model           TEXT,
  permission_mode TEXT
);

INSERT INTO snapshots_new
  (id, branch, kind, code_pin, apm_lock_hash,
   author, created_at, format_version, model, permission_mode)
SELECT
   id,
   branch,
   kind,
   code_pin,
   apm_lock_hash,
   author,
   created_at,
   format_version,
   model,
   permission_mode
FROM snapshots
WHERE kind != 'tag';

DROP INDEX IF EXISTS idx_snapshots_branch;
DROP INDEX IF EXISTS idx_snapshots_created_at;
DROP INDEX IF EXISTS idx_snapshots_kind;
DROP INDEX IF EXISTS idx_snapshots_apm_lock;

DROP TABLE snapshots;
ALTER TABLE snapshots_new RENAME TO snapshots;

CREATE INDEX idx_snapshots_branch     ON snapshots(branch);
CREATE INDEX idx_snapshots_created_at ON snapshots(created_at);
CREATE INDEX idx_snapshots_kind       ON snapshots(kind);
CREATE INDEX idx_snapshots_apm_lock   ON snapshots(apm_lock_hash);

-- ─────────────────────────────────────────────────────────────────────
-- Bump schema version. Verify FK integrity before commit.
-- ─────────────────────────────────────────────────────────────────────

UPDATE _schema SET version = 5;

PRAGMA foreign_key_check;

COMMIT;

PRAGMA foreign_keys = ON;
